<?php
/**
 * @file
 * Module that filters empty HTML tags and extra non-breaking spaces.
 */

 /**
  * Implementation of hook_filter().
  */
 function extraspace_filter_filter($op, $delta = 0, $format = -1, $text = '', $cache_id = 0) {
  switch ($op) {
    case 'list':
      return array(0 => t('Extra space filter'));

    case 'description':
      return t('Filters empty HTML tags and extra non-breaking spaces.');

    case "process":
      // Remove empty paragraph tags
      $text = preg_replace('/\<p(\s[^\>]*)*\>(\s|\xC2\xA0|&nbsp;)*\<\/p\>/i', '', $text);

      // Remove multiple non-breaking spaces
      $text = preg_replace('/(&nbsp;)(\n|\r|\t|\s|\xC2\xA0|&nbsp;)+/i', '$1', $text);

      // Remove multiple line-breaks
      // Cleanup beginnings of paragraphs
      $text = preg_replace('/(\<br\>|\<br \/\>|\<p\>)(\n|\r|\t|\s|\xC2\xA0|&nbsp;|\<br\>|\<br \/\>)+/i', '$1', $text);

      return $text;

    default:
      return $text;
  }
}
